### ISSUE TITLE
dmd 2.060 fails

### ISSUE THREAD

**Issue by mroosmalen** [lomereiter/BioD#3]
If I try to compile one of the example scripts like, create_bam_from_scratch.d  (OpenSuse 13.2 , dmd 2.060) 

dmd examples/create_bam_from_scratch.d 

It fails with the next message:

bio/bam/thirdparty/msgpack.d(1536): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(1541): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(1582): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(1587): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(2947): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(2952): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(2984): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(2989): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(3742): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
bio/bam/thirdparty/msgpack.d(3777): Error: valid attribute identifiers are @property, @safe, @trusted, @system, @disable not @nonPacked
Error: template bio.bam.thirdparty.msgpack.unpack(bool withFieldName = false,Args...) conflicts with function bio.bam.thirdparty.msgpack.unpack at bio/bam/thirdparty/msgpack.d(149)
Error: template bio.bam.thirdparty.msgpack.unpack(Type,bool withFieldName = false) conflicts with function bio.bam.thirdparty.msgpack.unpack at bio/bam/thirdparty/msgpack.d(149)
Failed: 'dmd' '-v' '-o-' 'examples/create_bam_from_scratch.d' '-Iexamples'

**Comment by lomereiter** [comment]
1) 2.060 is too old, 2.066 has bugs, but it should compile with 2.065
2) The recommended compiler is LDC and not DMD
3) This repository is outdated, please post issues to http://github.com/BioD/BioD
